### PR TITLE
Added the down removal margin as a configuration

### PR DESCRIPTION
**Pull request by borgmatthew**
This is a simple fix for #19 . I've added the configuration in the conf file but it is not being used anywhere except for the overridden method.

### CODE REVIEW

**Comment by TanUkkii007** [comment]
Thanks!
Let's fix stackoverflow first. I'll merge this PR but I have to confirm `down-removal-margin` usages in custom downing provider.

**Comment by TanUkkii007** [comment]
I'm still not sure about `down-removal-margin` usage in custom downing providers.

> The purpose of this margin is that
 in case of a network partition the persistent actors in the non-surviving partitions
 must be stopped before corresponding persistent actors are started somewhere else.
 This is useful if you implement downing strategies that handle network partitions,
 e.g. by keeping the larger side of the partition and shutting down the smaller side.

My understanding is that `down-removal-margin` is used in cluster extensions like cluster sharding
 to give a time for persistent actors to shutdown in non-surviving partition
 by suspending failover of dead persistent actors in surviving partition.
This sounds like `down-removal-margin` handling is up to extension layers and make me confused.

If I'm correct what `akka-cluster-custom-downing` should do is to suspend resolutions of surviving partition
 by `down-removal-margin` seconds, while immediately shutdown a non-surviving partition.
 In this way a cluster coordinator in surviving partition waits to failover persistent actors until resolutions.

What do you think, @borgmatthew ?

**Comment by borgmatthew** [comment]
It is confusing, I agree. I did some research and found the following code in the `ClusterSingletonManager.scala`:

`val removalMargin =
    if (settings.removalMargin <= Duration.Zero) cluster.downingProvider.downRemovalMargin
    else settings.removalMargin`

If my understanding is correct, the `downRemovalMargin` should only be used by the inner workings of the akka cluster (such as the `ClusterSingletonManager`). I don't think that `akka-cluster-custom-downing` should do anything with the `downRemovalMargin` (other than load it from the configuration file). I think that the `akka.cluster.down-removal-margin` was removed as not every resolution strategy might use it.

Do you agree @TanUkkii007 ?

**Comment by TanUkkii007** [comment]
@borgmatthew 
Thanks for your information. I understand your point.
Then let us leave `down-removal-margin` handling as the current implementation, rather than introduce an extra complexity.

**Pull request merged**
