### PR TITLE
Added MajorityLeaderAutoDowning

### PR DESCRIPTION
**Pull request by peteremiljensen**
Added the auto-downing strategy corresponding to keep-majority in Akka's Split Brain Resolvers. Checked by normal and multi-node tests as well.

### CODE REVIEW

**Comment by TanUkkii007** [comment]
Thank you for your contribution!

**Comment by TanUkkii007** [comment]
By the way you can update README if you do not mind.

**Comment by peteremiljensen** [comment]
Thank you and no problem. Refer to #10

**Comment by TanUkkii007** [comment]
Released in version 0.0.8.

**Pull request merged**
